# Generated by Django 5.2.9 on 2025-12-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_dx', models.BooleanField(default=False, verbose_name='DX 접근 권한')),
                ('can_access_ds', models.BooleanField(default=False, verbose_name='DS 접근 권한')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('is_locked', models.BooleanField(default=False, verbose_name='계정 잠금')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='잠금 시간')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
