# Generated by Django 5.2.9 on 2026-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_report',
            field=models.BooleanField(default=False, verbose_name='모니터링 보고 권한'),
        ),
    ]
