# Generated by Django 5.2.9 on 2026-02-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_can_access_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_report',
        ),
    ]
