"""
데이터 수집 스케줄 정의 (PDF 기반)
"""

# 공통
COMMON_SCHEDULE = [
    {
        'name': '이벤트 정보',
        'description': '국가 내 주요 이벤트 정보 (이벤트명, 이벤트일, 이벤트주)',
        'source': 'LLM',
        'table': 'openai_event_mst',
        'view': 'openai_event_mst_view',
        'frequency': 'Daily',
        'time': '18:00',
        'category': 'common',
    },
    {
        'name': '경쟁 신제품 리스트(TV)',
        'description': '자사 신제품에 매핑되는 경쟁 제품 리스트 [북미]',
        'source': 'LLM',
        'table': 'market_comp_product',
        'view': 'market_comp_product_view',
        'frequency': 'Quarterly',
        'time': '09:00',
        'category': 'common',
        'product_line': 'TV',
    },
    {
        'name': '경쟁 신제품 리스트(HHP)',
        'description': '자사 신제품에 매핑되는 경쟁 제품 리스트 [북미]',
        'source': 'LLM',
        'table': 'market_comp_product',
        'view': 'market_comp_product_view',
        'frequency': 'Quarterly',
        'time': '09:00',
        'category': 'common',
        'product_line': 'HHP',
    },
]

# Market - 시장 분석
MARKET_SCHEDULE = [
    {
        'name': '수요 증감율 예측(TV)',
        'description': 'LLM 기반 수요 예측 [북미]',
        'source': 'LLM',
        'table': 'openai_forecast_results',
        'view': 'openai_forecast_results_view',
        'frequency': 'Weekly',
        'time': '18:00',
        'category': 'market',
        'product_line': 'TV',
    },
    {
        'name': '수요 증감율 예측(HHP)',
        'description': 'LLM 기반 수요 예측 [북미]',
        'source': 'LLM',
        'table': 'openai_forecast_results',
        'view': 'openai_forecast_results_view',
        'frequency': 'Weekly',
        'time': '18:00',
        'category': 'market',
        'product_line': 'HHP',
    },
    {
        'name': '거래선 프로모션 정보',
        'description': 'Amazon, BestBuy, Walmart 등 7개 거래선',
        'source': 'LLM',
        'table': 'openai_retailer_promotions',
        'view': 'openai_retailer_promotions_view',
        'frequency': 'Weekly',
        'time': '18:00',
        'category': 'market',
    },
    {
        'name': '경쟁 신제품 출시 정보(TV)',
        'description': '경쟁사 신제품 사전예약/출시일 [북미]',
        'source': 'LLM',
        'table': 'market_comp_event',
        'view': 'market_comp_event_view',
        'frequency': 'Monthly',
        'time': '09:00',
        'category': 'market',
        'product_line': 'TV',
    },
    {
        'name': '경쟁 신제품 출시 정보(HHP)',
        'description': '경쟁사 신제품 사전예약/출시일 [북미]',
        'source': 'LLM',
        'table': 'market_comp_event',
        'view': 'market_comp_event_view',
        'frequency': 'Monthly',
        'time': '09:00',
        'category': 'market',
        'product_line': 'HHP',
    },
    {
        'name': '키워드 검색 트렌드(TV)',
        'description': '키워드 검색 수 트렌드 [북미]',
        'source': 'Bing News',
        'table': 'market_trend',
        'view': 'market_trend_view',
        'frequency': 'Daily',
        'time': '23:00',
        'category': 'market',
        'product_line': 'TV',
    },
    {
        'name': '키워드 검색 트렌드(HHP)',
        'description': '키워드 검색 수 트렌드 [북미]',
        'source': 'Bing News',
        'table': 'market_trend',
        'view': 'market_trend_view',
        'frequency': 'Daily',
        'time': '23:00',
        'category': 'market',
        'product_line': 'HHP',
    },
]

# Retail - 리테일 데이터
RETAIL_SCHEDULE = [
    {
        'name': '거래선 TV 제품 정보 (Amazon)',
        'description': 'Amazon 크롤링 [북미]',
        'source': 'Amazon',
        'table': 'tv_retail_com',
        'view': 'tv_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'TV',
        'retailer': 'Amazon',
    },
    {
        'name': '거래선 TV 제품 정보 (Bestbuy)',
        'description': 'Bestbuy 크롤링 [북미]',
        'source': 'Bestbuy',
        'table': 'tv_retail_com',
        'view': 'tv_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'TV',
        'retailer': 'Bestbuy',
    },
    {
        'name': '거래선 TV 제품 정보 (Walmart)',
        'description': 'Walmart 크롤링 [북미]',
        'source': 'Walmart',
        'table': 'tv_retail_com',
        'view': 'tv_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'TV',
        'retailer': 'Walmart',
    },
    {
        'name': '거래선 HHP 제품 정보 (Amazon)',
        'description': 'Amazon 크롤링 [북미]',
        'source': 'Amazon',
        'table': 'hhp_retail_com',
        'view': 'hhp_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'HHP',
        'retailer': 'Amazon',
    },
    {
        'name': '거래선 HHP 제품 정보 (Bestbuy)',
        'description': 'Bestbuy 크롤링 [북미]',
        'source': 'Bestbuy',
        'table': 'hhp_retail_com',
        'view': 'hhp_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'HHP',
        'retailer': 'Bestbuy',
    },
    {
        'name': '거래선 HHP 제품 정보 (Walmart)',
        'description': 'Walmart 크롤링 [북미]',
        'source': 'Walmart',
        'table': 'hhp_retail_com',
        'view': 'hhp_retail_com_view',
        'frequency': 'Daily',
        'time': '00:00',
        'category': 'retail',
        'product_line': 'HHP',
        'retailer': 'Walmart',
    },
    {
        'name': '거래선 TV 제품 감성점수',
        'description': 'LLM 기반 감성분석',
        'source': 'LLM',
        'table': 'tv_retail_com',
        'view': 'tv_retail_com_view',
        'frequency': 'Daily',
        'time': '01:00',
        'category': 'retail',
        'product_line': 'TV',
        'check_field': 'sentiment_score',
    },
    {
        'name': '거래선 HHP 제품 감성점수',
        'description': 'LLM 기반 감성분석',
        'source': 'LLM',
        'table': 'hhp_retail_com',
        'view': 'hhp_retail_com_view',
        'frequency': 'Daily',
        'time': '01:00',
        'category': 'retail',
        'product_line': 'HHP',
        'check_field': 'sentiment_score',
    },
]

# Consumer - 소비자 동향
CONSUMER_SCHEDULE = [
    {
        'name': 'YouTube 영상 데이터(TV)',
        'description': 'API 기반 영상 데이터 수집 [북미]',
        'source': 'API',
        'tables': ['youtube_videos_raw', 'youtube_videos', 'youtube_comments'],
        'views': ['youtube_videos_raw_view', 'youtube_videos_view', 'youtube_comments_view'],
        'frequency': 'Daily',
        'time': '12:00',
        'category': 'consumer',
        'product_line': 'TV',
    },
    {
        'name': 'YouTube 영상 데이터(HHP)',
        'description': 'API 기반 영상 데이터 수집 [북미]',
        'source': 'API',
        'tables': ['youtube_videos_raw', 'youtube_videos', 'youtube_comments'],
        'views': ['youtube_videos_raw_view', 'youtube_videos_view', 'youtube_comments_view'],
        'frequency': 'Daily',
        'time': '12:00',
        'category': 'consumer',
        'product_line': 'HHP',
    },
]

# Macro - 거시경제 지표 (10대 인자)
MACRO_SCHEDULE = [
    {
        'name': '명목 GDP (PPP 기준) 1인당',
        'description': 'Nominal GDP - 직전년도 수치, 전체 국가',
        'source': 'World Bank',
        'table': 'market_gdp_ppp_nominal',
        'view': 'market_gdp_ppp_nominal_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '실질 GDP (PPP 기준) 1인당',
        'description': 'Real GDP - 직전년도 수치, 전체 국가',
        'source': 'World Bank',
        'table': 'market_gdp_ppp_real',
        'view': 'market_gdp_ppp_real_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '자본 스톡 (실질, PPP 기준)',
        'description': 'Capital Stock - 직전년도 수치, 전체 국가',
        'source': 'IMF',
        'table': 'market_capital_stock',
        'view': 'market_capital_stock_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '잠재적 산출량 (PPP 기준)',
        'description': 'Potential Output - 기준일 이후 5개년 전망치',
        'source': 'OECD',
        'table': 'market_potential_gdp',
        'view': 'market_potential_gdp_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '개인 가처분 소득 (실질, PPP 환산)',
        'description': 'Personal Disposable Income, Real - 직전년도 수치',
        'source': 'World Bank',
        'table': 'market_disposable_income_real',
        'view': 'market_disposable_income_real_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '소비자 물가 지수 (CPI)',
        'description': 'Consumer Price Index - 직전년도 수치',
        'source': 'World Bank',
        'table': 'market_cpi',
        'view': 'market_cpi_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '소매 가격 지수 (RPI)',
        'description': 'Retail Price Index - 직전 3개월, 미국/영국',
        'source': 'FRED',
        'table': 'market_rpi',
        'view': 'market_rpi_view',
        'frequency': 'Monthly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '개인 처분 가능 소득 (명목)',
        'description': 'Personal Disposable Income, Nominal - 직전년도 수치',
        'source': 'World Bank',
        'table': 'market_disposable_income_nominal',
        'view': 'market_disposable_income_nominal_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '가계부문 기타 금융부채 (LCU)',
        'description': 'Household Sector Other Financial Liabilities - 직전년도 수치',
        'source': 'World Bank',
        'table': 'market_household_debt',
        'view': 'market_household_debt_view',
        'frequency': 'Yearly',
        'time': '09:00',
        'category': 'macro',
    },
    {
        'name': '민간부문 순 이자수입 (LCU)',
        'description': 'Private Sector Net Interest Income - 직전 2개 분기',
        'source': 'IMF',
        'table': 'market_net_interest',
        'view': 'market_net_interest_view',
        'frequency': 'Quarterly',
        'time': '09:00',
        'category': 'macro',
    },
]

# 전체 스케줄
ALL_SCHEDULES = COMMON_SCHEDULE + MARKET_SCHEDULE + RETAIL_SCHEDULE + CONSUMER_SCHEDULE + MACRO_SCHEDULE


def get_schedule_by_category(category):
    """카테고리별 스케줄 반환"""
    return [s for s in ALL_SCHEDULES if s.get('category') == category]


def get_daily_schedules():
    """일일 수집 스케줄만 반환"""
    return [s for s in ALL_SCHEDULES if s.get('frequency') == 'Daily']
