SEA_RETAIL_TABLES = {
    'tv': {
        'table': 'tv_retail_com',
        'date_column': 'crawl_datetime',
        'retailers': ['Amazon', 'Bestbuy', 'Walmart'],
        'expected': {'Amazon': 300, 'Bestbuy': 300, 'Walmart': 300},
        'table_view': 'RAW_EXT_TV_RETAIL_COM_VIEW',
    },
    'ref': {
        'table': 'ref_retail_com',
        'date_column': 'crawl_strdatetime',
        'retailers': ['Bestbuy', 'Lowes'],
        'expected': {'Bestbuy': 300, 'Lowes': 300},
        'table_view': 'RAW_EXT_REF_RETAIL_COM_VIEW',
    },
    'ldy': {
        'table': 'ldy_retail_com',
        'date_column': 'crawl_strdatetime',
        'retailers': ['Bestbuy', 'Lowes'],
        'expected': {'Bestbuy': 260, 'Lowes': 260},
        'table_view': 'RAW_EXT_LDY_RETAIL_COM_VIEW',
    },
}

SEA_RETAIL_NULL_COLUMNS = {
    'ref': {
        'Bestbuy': [
            'count_of_reviews',
            'retailer_sku_name',
            'star_rating',
            'count_of_star_ratings',
            'final_sku_price',
            'original_sku_price',
            'savings',
            'pick_up_availability',
            'delivery_availability',
            'sku_status',
            'detailed_review_content',
            'recommendation_intent',
            'main_rank',
            'bsr_rank',
            'retailer_sku_name_similar',
            'ref_capacity',
            'ref_refrigerator_type',
            'sku',
            'offer',
        ],
        'Lowes': [
            'count_of_reviews',
            'retailer_sku_name',
            'star_rating',
            'count_of_star_ratings',
            'final_sku_price',
            'original_sku_price',
            'savings',
            'pick_up_availability',
            'delivery_availability',
            'sku_status',
            'detailed_review_content',
            'recommendation_intent',
            'main_rank',
            'bsr_rank',
            'retailer_sku_name_similar',
            'ref_capacity',
            'ref_refrigerator_type',
            'discount_type',
            'sku_popularity',
            'sku',
            'number_of_units_purchased_past_week',
            'fastest_delivery',
            'available_quantity_for_purchase_pickup',
            'available_quantity_for_purchase_delivery',
            'available_quantity_for_purchase_fastdelivery',
            'summarized_review_content',
        ],
    },
    'ldy': {
        'Bestbuy': [
            'count_of_reviews',
            'retailer_sku_name',
            'star_rating',
            'count_of_star_ratings',
            'final_sku_price',
            'original_sku_price',
            'savings',
            'pick_up_availability',
            'delivery_availability',
            'sku_status',
            'detailed_review_content',
            'recommendation_intent',
            'main_rank',
            'bsr_rank',
            'retailer_sku_name_similar',
            'ldy_capacity',
            'ldy_loading_type',
            'sku',
            'offer',
        ],
        'Lowes': [
            'count_of_reviews',
            'retailer_sku_name',
            'star_rating',
            'count_of_star_ratings',
            'final_sku_price',
            'original_sku_price',
            'savings',
            'pick_up_availability',
            'delivery_availability',
            'sku_status',
            'detailed_review_content',
            'recommendation_intent',
            'main_rank',
            'bsr_rank',
            'retailer_sku_name_similar',
            'ldy_capacity',
            'ldy_loading_type',
            'discount_type',
            'sku_popularity',
            'sku',
            'number_of_units_purchased_past_week',
            'fastest_delivery',
            'available_quantity_for_purchase_pickup',
            'available_quantity_for_purchase_delivery',
            'available_quantity_for_purchase_fastdelivery',
            'summarized_review_content',
        ],
    },
}


def get_sea_retail_config(product_line):
    return SEA_RETAIL_TABLES.get(product_line.lower())


def get_sea_retail_null_columns(product_line, retailer):
    return SEA_RETAIL_NULL_COLUMNS.get(product_line.lower(), {}).get(retailer, [])
